manifest:
  escc_immun: config/samples_ESCC_IM.txt
  escc_epi: config/samples_ESCC_EP.txt
  gej_immun: config/samples_GEJ_IM.txt
  gej_epi: config/samples_GEJ_EP.txt
  lowqual_sample: config/lowqual_sample_basedonMitoPerc.txt

# subdirectories
dir:
  rawdata: ESCC_GEJ_cellRanger_out
  data: data
  log: log
  qc: plot/qc
  plot: plot
  resources: resources
  scripts: scripts

# qc strategy
qc:
  all_sample: false
  cal_outlyingness: false
  #target: merged
  target: outlyflted
  strategy: pipe
  nCell: 10
  nUMI_lo: 1000
  nUMI_up: 100000
  nGene_lo: 200
  nGene_up: 10000
  log10GenesPerUMI: 0.8
  mitoCountRatio: 0.2

# normalization strategies
norm:
  regressNum: true #whether to include nGene and nUMI in SCTransform var.regress
  sctPreNorm: true    #whether to run SCTranform before calculating cell cycle scores
  maxPC: 30
  perSample: true  #sample-level normalization then integrate
  findAnchor: rpca
  method: sctNorm

# batch correction
batchRm:
  nFeature: 2000
  seurat3_anchor: cca

# evaluate clustering stability
stable:
  subsample_rate: 0.8
  num_of_subsample: 20
  #subsample_k: 50
  subsample_k: 20,50,80 
  #subsample_k: 50,100,150
  subsample_resolution: 0.2,0.4,0.6,0.8,1
  #subsample_resolution: 0.05,0.15,0.25
  #subsample_resolution: 0.05
  subsample_pc: 10,30,50
  #subsample_pc: 10,20
  #subsample_pc: 20
  PreprocessSubsetData_subsample_pars: "variable.features.n = 3000, score.thresh = 1e-5, n.start = 100, nn.eps = 0"
  #input_seurat: GEJ_QCed_sctNorm_BatchCCA
  stability_dimReduct: "reduc=\"pca\""
  #input_seurat: ESCC_QCed_sctNorm_BatchHmy
  input_seurat: ESCC_14patients_TDN
  #input_seurat: ESCC_jiaoda_GSE145370
  #stability_dimReduct: "reduc=\"harmony\""
  #stability_dimReduct: "reduc=\"glmpca\""

# Comment out to not assign cell type via signatures
celltype:
  # Table describing markers for assignment of cell types.
  # Columns: name (cell type name), parent (parent cell type name),
  #          genes (comma-separated list of gene names/ids, as listed in the
  #          count matrix)
  # Thereby, parent is usually empty. If not, it means that assignment for that
  # type happens recursively only on those cells that have been assigned to the
  # parent type.
  markers: resources/markers.tsv
  # Minimum gamma score for assigned cell type (resembles a posterior) to be
  # considered as correctly assigned. Cells where the certainty of cellassign
  # does not pass this threshold will show as celltype=NA.
  min_gamma: 0.9
  # Genes to create expression plots stratified by celltype for.
  # This can be used to find the right selection of marker genes for cellassign.
  expression-plot-genes:
    - GBP1
    - MYCN

gene-vs-gene-plots:
  all-malignant:
    # uncomment below to perform a correlation of given type (pearson, spearman, ...)
    correlation: spearman
    # uncomment below to perform a regression with given formula
    # regression: "y ~ x"
    # constrain to cells of the following types (comment out if not needed)
    constrain-celltypes:
      - Malignant
    pairs:
      x: DDX58
      y:
        - IRF1
        - CCL5
        - CXCL10


# Comment out to not do differential expression analysis.
diffexp:
  # Add one entry per comparison here. The key below can be an arbitrary name.
  a-vs-b:
    # EdgeR design formula.
    # Refer to any colData from SingleCellExperiment here.
    # In addition, you can use celltype and detection_rate
    # (number of expressed genes in cell divided by total
    # number of genes in experiment).
    design: "~ test.condition"
    # Which coefficients of the model should be tested equal to zero.
    # E.g., 2 to test the first coefficient after the implicit intercept
    # (i.e., celltype in the example above).
    coef: 2
    # False discovery rate to control for.
    fdr: 0.05
    # Optional: constrain to cell types (comment out to use all cell types).
    constrain-celltypes:
      celltypes:
        - Endothelial-cell
      # Optional: constrain cells to those with the given covariate occurring in all celltypes 
      # (comment in if needed).
      # This can be used to avoid confounding of an important batch variable.
      # E.g., if you want the differential expression across cell types, and sample is a 
      # batch variable to control for, you need to ensure that each sample contains all
      # considered cell types.
      # common: sample
    # Genes to plot
    genes_of_interest:
      - MITF
      - MYCN
